
version: '3.8'

services:
  # ----------- CONTENEDORES EN LA RED "red-frio" -----------
  frio1:
    image: alpine:3.22
    container_name: frio1
    networks:
      - red-frio
    command: sh -c "while true; do sleep 3600; done"

  frio2:
    image: alpine:3.22
    container_name: frio2
    networks:
      - red-frio
    command: sh -c "while true; do sleep 3600; done"

  frio3:
    image: alpine:3.22
    container_name: frio3
    networks:
      - red-frio
    command: sh -c "while true; do sleep 3600; done"

  frio4:
    image: alpine:3.22
    container_name: frio4
    networks:
      - red-frio
    command: sh -c "while true; do sleep 3600; done"

  # ----------- CONTENEDORES EN LA RED "red-caliente" -----------
  cal1:
    image: alpine:3.22
    container_name: cal1
    networks:
      - red-caliente
    command: sh -c "while true; do sleep 3600; done"

  cal2:
    image: alpine:3.22
    container_name: cal2
    networks:
      - red-caliente
    command: sh -c "while true; do sleep 3600; done"

  cal3:
    image: alpine:3.22
    container_name: cal3
    networks:
      - red-caliente
    command: sh -c "while true; do sleep 3600; done"

  cal4:
    image: alpine:3.22
    container_name: cal4
    networks:
      - red-caliente
    command: sh -c "while true; do sleep 3600; done"

  # ----------- CONTENEDOR CON CONEXIÓN A LAS TRES REDES -----------
  puente1:
    image: alpine:3.22
    container_name: puente1
    networks:
      - red-frio
      - red-caliente
      - tibio
    command: sh -c "while true; do sleep 3600; done"

# ----------- DEFINICIÓN DE REDES PERSONALIZADAS -----------
networks:
  red-frio:
    driver: bridge
  red-caliente:
    driver: bridge
  tibio:
    driver: bridge
