version: '3.8'  # Versión del esquema de Docker Compose

services:
  # ----------- CONTENEDORES EN LA RED "red-frio" -----------
  frio1:
    image: alpine:3.22  # Imagen base: Alpine Linux versión 3.22 (ligera y rápida)
    container_name: frio1  # Nombre del contenedor (visible con docker ps)
    networks:
      - red-frio  # Conectado únicamente a la red 'red-frio'
    command: sh -c "while true; do sleep 3600; done"  # Mantiene el contenedor en ejecución con un bucle infinito

  frio2:
    image: alpine:3.22
    container_name: frio2
    networks:
      - red-frio
    command: sh -c "while true; do sleep 3600; done"

  frio3:
    image: alpine:3.22
    container_name: frio3
    networks:
      - red-frio
    command: sh -c "while true; do sleep 3600; done"

  frio4:
    image: alpine:3.22
    container_name: frio4
    networks:
      - red-frio
    command: sh -c "while true; do sleep 3600; done"

  # ----------- CONTENEDORES EN LA RED "red-caliente" -----------
  cal1:
    image: alpine:3.22
    container_name: cal1
    networks:
      - red-caliente  # Conectado únicamente a la red 'red-caliente'
    command: sh -c "while true; do sleep 3600; done"

  cal2:
    image: alpine:3.22
    container_name: cal2
    networks:
      - red-caliente
    command: sh -c "while true; do sleep 3600; done"

  cal3:
    image: alpine:3.22
    container_name: cal3
    networks:
      - red-caliente
    command: sh -c "while true; do sleep 3600; done"

  cal4:
    image: alpine:3.22
    container_name: cal4
    networks:
      - red-caliente
    command: sh -c "while true; do sleep 3600; done"

# ----------- DEFINICIÓN DE LAS REDES PERSONALIZADAS -----------
networks:
  red-frio:
    driver: bridge  # Tipo de red: 'bridge' permite comunicación entre contenedores en la misma red
  red-caliente:
    driver: bridge
